### PR TITLE
fix style scoped

### LINKED ISSUE #2: Scoped style not supported
Hi @Morgul 

Your clean approach described in the README looks nice. I felt on your plugin trying to use snowpack and avoid webpack slowness in our devs. 

So I did notice that `<style scoped>` is not working. It seems to come from a wider problem which is not reflected in your paragraph: https://github.com/Morgul/snowpack-plugin-vue2#vue-library-choice. That problem is that `@vue/compiler-sfc` does things that were not backported with `@vue/component-compiler-utils`, its Vue 2 false equivalent. They are similarities between `SFCTemplateCompileOptions` (1) and `TemplateCompileOptions` (2) but the scoped style feature lacks.

With webpack it worked because `vue-loader` precisely fulfills those discrepancies. I am not even sure that requesting you this feature (roughly to copy vue-loader work (3)) is the best solution. Shouldn't this have been done directly within `@vue/component-compiler-utils`?

1. https://github.com/vuejs/vue-next/blob/master/packages/compiler-sfc/src/compileTemplate.ts#L43
2. https://github.com/vuejs/component-compiler-utils#compiletemplatetemplatecompileoptions-templatecompileresults
3. https://github.com/vuejs/vue-loader/blob/master/lib/index.js#L163

### PR DESCRIPTION
**Pull request by eytienne**
Fixes https://github.com/Morgul/snowpack-plugin-vue2/issues/2

I finally found the hidden property used in a "[less] formal engineered solution". ;)
It works like a charm now but was a bit messy to find out ─ long live TypeScript!

### CODE REVIEW

File: compiler/index.js [hunk 1]
```diff
@@ -45,7 +45,8 @@ function $compileTemplate(options)
     // This is done manually in @vue/compiler-sfc, but controlled by a boolean in `@vue/component-compiler-utils`. So,
     // we ignore all the hard work the plugin did, and just toggle a boolean so the compiler will redo the work. Eh, as
     // far as hacks go, this isn't the worst.
```
Comment (eytienne) [inline compiler/index.js:49]: Not sure about this part and the veracity of the comment

**Comment by Morgul** [comment]
I'm ok with repeating some of vue-loder's work, to make things equivalent. Thanks for this!
